[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

# Testing
verbosity = 2
fuzz_runs = 256
ffi = false

# Formatting
line_length = 100
tab_width = 4
bracket_spacing = false

[rpc_endpoints]
mainnet = "${ETHEREUM_MAINNET_RPC}"
sepolia = "${SEPOLIA_RPC}"
arbitrum = "${ARBITRUM_RPC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
